# Generated by Django 3.2.3 on 2021-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=500)),
                ('datetime_crawled', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
